const data={
    products:[
        {
            _id:"1",
            name: "YSL Small Bag",
            category: 'Bag',
            image: '/images/p1.jpg',
            price: 750.00,
            countInStock: 10,
            brand: 'YSL',
            rating: 4.5,
            numReview: 10,
            description: 'Top Grade'
        },
        {
            _id:"2",
            name: "Christian Dior Wallet",
            category: 'Wallet',
            image: '/images/p2.jpg',
            price: 350.00,
            countInStock: 3,
            brand: 'Christian Dior',
            rating: 4.5,
            numReview: 6,
            description: 'Top Grade'
        },
        {
            _id:"3",
            name: "Chanel Wallet",
            category: 'Wallet',
            image: '/images/p3.jpg',
            price: 350.00,
            countInStock: 18,
            brand: 'Chanel',
            rating: 2,
            numReview: 17,
            description: 'Top Grade'
        },
        {
            _id:"4",
            name: "Gucci Mens Wallet",
            category: 'Wallet',
            image: '/images/p4.jpg',
            price: 300.00,
            countInStock: 12,
            brand: 'Gucci',
            rating: 5,
            numReview: 8,
            description: 'Top Grade'
        },
        {
            _id:"5",
            name: "Prada Mens Wallet",
            category: 'Wallet',
            image: '/images/p5.jpg',
            price: 300.00,
            countInStock: 5,
            brand: 'Prada',
            rating: 4.5,
            numReview: 13,
            description: 'Top Grade'
        },
        {
            _id:"6",
            name: "LV Mens Wallet",
            category: 'Wallet',
            image: '/images/p6.jpg',
            price: 300.00,
            countInStock: 7,
            brand: 'Louis Vuitton',
            rating: 4,
            numReview: 10,
            description: 'Top Grade'
        },
        {
            _id:"7",
            name: "LV Medium Wallet",
            category: 'Wallet',
            image: '/images/p7.jpg',
            price: 350.00,
            countInStock: 16,
            brand: 'Louis Vuitton',
            rating: 3,
            numReview: 15,
            description: 'Top Grade'
        },
        {
            _id:"8",
            name: "Fendi Sling bag",
            category: 'Bag',
            image: '/images/p8.jpg',
            price: 650.00,
            countInStock: 5,
            brand: 'Fendi',
            rating: 3.5,
            numReview: 6,
            description: 'Top Grade'
        },
        {
            _id:"9",
            name: "Christian Dior tote bag",
            category: 'Bag',
            image: '/images/p9.jpg',
            price: 800.00,
            countInStock: 1,
            brand: 'Christian Dior',
            rating: 5,
            numReview: 18,
            description: 'Top Grade'
        },
        {
            _id:"10",
            name: "LV Papillon Trunk (M)",
            category: 'Bag',
            image: '/images/p10.jpg',
            price: 750.00,
            countInStock: 6,
            brand: 'Louis Vuitton',
            rating: 3.5,
            numReview: 8,
            description: 'Top Grade'
        },
        {
            _id:"11",
            name: "LV Handbag (M)",
            category: 'Bag',
            image: '/images/p11.jpg',
            price: 750.00,
            countInStock: 6,
            brand: 'Louis Vuitton',
            rating: 1,
            numReview: 1,
            description: 'Top Grade'
        },
        {
            _id:"12",
            name: "GG Doraemon SlingBag",
            category: 'Bag',
            image: '/images/p12.jpg',
            price: 650.00,
            countInStock: 20,
            brand: 'Gucci Gang',
            rating: 0,
            numReview: 0,
            description: 'Top Grade'
        },
        {
            _id:"13",
            name: "LV Alma Handbag",
            category: 'Bag',
            image: '/images/p13.jpg',
            price: 800.00,
            countInStock: 0,
            brand: 'Louis Vuitton',
            rating: 5,
            numReview: 20,
            description: 'Top Grade'
        },
        {
            _id:"14",
            name: "LV Papillon Trunk (D)",
            category: 'Bag',
            image: '/images/p14.jpg',
            price: 750.00,
            countInStock: 9,
            brand: 'Louis Vuitton',
            rating: 3.5 ,
            numReview: 6,
            description: 'Top Grade'
        },
        {
            _id:"15",
            name: "Coach Slingbag",
            category: 'Bag',
            image: '/images/p15.jpg',
            price: 550.00,
            countInStock: 8,
            brand: 'Coach',
            rating: 3.5,
            numReview: 12,
            description: 'Top Grade'
        },
        {
            _id:"16",
            name: "Fendi Belt Bag",
            category: 'Bag',
            image: '/images/p16.jpg',
            price: 550.00,
            countInStock: 14,
            brand: 'Fendi',
            rating: 2.5,
            numReview: 4,
            description: 'Top Grade'
        },
        {
            _id:"17",
            name: "LV Dauphine Handbag", 
            category: 'Bag',
            image: '/images/p17.jpg',
            price: 750.00,
            countInStock: 8,
            brand: 'Louis Vuitton',
            rating: 4,
            numReview: 18,
            description: 'Top Grade'
        },
        {
            _id:"18",
            name: "Coach Madison Sling",
            category: 'Bag',
            image: '/images/p18.jpg',
            price: 650.00,
            countInStock: 5,
            brand: 'Coach',
            rating: 2.5,
            numReview: 11,
            description: 'Top Grade'
        },
    ]
}
export default data;